server:
  port: 8999
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.17.14:9876
        bindings:
          output:
            destination: rocketmq-test
            content-type: application/json

